### ISSUE TITLE
MultiBamSummary error message 

### ISSUE THREAD

**Issue by LouATK** [fidelram/deepTools#305] opened 2016-02-26 10:53 UTC
Hi, 

I have tried to run  MultiBamSummary with 6 Bam files but returned this error message:

toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_multi_bam_summary/deeptools_multi_bam_summary/2.1.0.0	slurm	17153
Remote Host
143.117.233.133
Command Line
ln -s "/home/galaxy/galaxy-dist/database/files/037/dataset_37576.dat" "./0.bam" && ln -s "/home/galaxy/galaxy-dist/database/files/_metadata_files/006/metadata_6059.dat" "./0.bam.bai" && ln -s "/home/galaxy/galaxy-dist/database/files/038/dataset_38669.dat" "./1.bam" && ln -s "/home/galaxy/galaxy-dist/database/files/_metadata_files/006/metadata_6060.dat" "./1.bam.bai" && ln -s "/home/galaxy/galaxy-dist/database/files/038/dataset_38138.dat" "./2.bam" && ln -s "/home/galaxy/galaxy-dist/database/files/_metadata_files/006/metadata_6061.dat" "./2.bam.bai" && ln -s "/home/galaxy/galaxy-dist/database/files/038/dataset_38111.dat" "./3.bam" && ln -s "/home/galaxy/galaxy-dist/database/files/_metadata_files/006/metadata_6062.dat" "./3.bam.bai" && ln -s "/home/galaxy/galaxy-dist/database/files/037/dataset_37958.dat" "./4.bam" && ln -s "/home/galaxy/galaxy-dist/database/files/_metadata_files/006/metadata_6063.dat" "./4.bam.bai" && ln -s "/home/galaxy/galaxy-dist/database/files/037/dataset_37807.dat" "./5.bam" && ln -s "/home/galaxy/galaxy-dist/database/files/_metadata_files/006/metadata_6064.dat" "./5.bam.bai" && multiBamSummary bins --numberOfProcessors "${GALAXY_SLOTS:-4}" --outFileName '/home/galaxy/galaxy-dist/database/files/070/dataset_70829.dat' --bamfiles '0.bam' '1.bam' '2.bam' '3.bam' '4.bam' '5.bam' --labels '1-BW-10 Tophat on data 4, data 26, and others: accepted_hits' '6-OV-12 Tophat on data 1, data 2, and others: accepted_hits' '5-OV-11 Tophat on data 1, data 2, and others: accepted_hits' '4-OV-10 Tophat on data 1, data 2, and others: accepted_hits' '3-BW-12 Tophat on data 1, data 2, and others: accepted_hits' '2-BW-11 Tophat on data 4, data 26, and others: accepted_hits' --outRawCounts '/home/galaxy/galaxy-dist/database/files/070/dataset_70830.dat' --binSize '10000' --distanceBetweenBins '0'
Stdout
Stderr
Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/home/galaxy/tool_dependency/deepTools/2.1.0/iuc/package_python_2_7_deeptools_2_1_0/2c54c7c38299/bin/multiBamSummary", line 7, in 
    main()
  File "/home/galaxy/tool_dependency/deepTools/2.1.0/iuc/package_python_2_7_deeptools_2_1_0/2c54c7c38299/lib/python/deeptools/multiBamSummary.py", line 219, in main
    num_reads_per_bin = c.run()
  File "/home/galaxy/tool_dependency/deepTools/2.1.0/iuc/package_python_2_7_deeptools_2_1_0/2c54c7c38299/lib/python/deeptools/countReadsPerBin.py", line 245, in run
    raise ValueError("numberOfSamples has to be bigger than {} ".format(min_num_of_samples))
ValueError: numberOfSamples has to be bigger than 29922 
```

Can anyone help/resolve? @mvdbeek recommended I post issue here.

Thanks!

**Comment by dpryan79** [comment] 2016-02-26 11:07
Can you decrease the bin size to 5000 (or 1000, if that doesn't work) and see if that solves the problem? This should be the "Bin size in bp" option.

**Comment by LouATK** [comment] 2016-02-26 11:27
Thanks @dpryan79 it is running now and encouragingly hasn't popped up an error message yet.

**Comment by dpryan79** [comment] 2016-02-26 11:54
That's something at least :)

Let me know whether it throws an error or not and I'll close the issue accordingly.

**Comment by fidelram** [comment] 2016-02-26 13:14
That error is caused by small scaffolds. Before running, the program checks that it can find at least n sampling points where n is the number of chromosomes. This was not thought for assemblies with large numbers of scaffolds.

**Comment by LouATK** [comment] 2016-02-26 13:47
Tool ran perfectly at 5000, thanks again @dpryan and @fidelram.

**Comment by dpryan79** [comment] 2016-02-26 13:49
Great, thanks for reporting back!

**Closed** 2016-02-26 13:49 UTC

**Comment by shauryajauhari** [comment] 2020-04-10 17:40
Soumyas-MacBook-Pro:transcriptionFactoriesGREG soumyajauhari$ bash ./terminalScripts/deepToolsmultiBAMSummaryGREG.sh ./GREG/A549/RNA-Seq/
[W::hts_idx_load2] The index file is older than the data file: ./GREG/A549/RNA-Seq//ENCFF761XXJ1.sorted.bam.bai
[W::hts_idx_load2] The index file is older than the data file: ./GREG/A549/RNA-Seq//ENCFF761XXJ1.sorted.bam.bai
Traceback (most recent call last):
  File "/usr/local/bin/multiBamSummary", line 14, in <module>
    main(args)
  File "/Library/Python/2.7/site-packages/deeptools/multiBamSummary.py", line 250, in main
    num_reads_per_bin = c.run(allArgs=args)
  File "/Library/Python/2.7/site-packages/deeptools/countReadsPerBin.py", line 339, in run
    chunkSize = self.get_chunk_length(bamFilesHandles, genomeSize, chromsizes, chrLengths)
  File "/Library/Python/2.7/site-packages/deeptools/countReadsPerBin.py", line 287, in get_chunk_length
    raise ValueError("numberOfSamples has to be bigger than {} ".format(min_num_of_samples))
ValueError: numberOfSamples has to be bigger than 197240

**Comment by dpryan79** [comment] 2020-04-10 21:01
@shauryajauhari Try decreasing the `-n` option from whatever you're using. This error will happen whenever the distance between bins is greater than the average chromosome length.

**Comment by shauryajauhari** [comment] 2021-01-06 18:39
There is no interleaving between the bins though and I have a contiguous chain of 2Kb intervals.
