### ISSUE TITLE
bamCoverage gives TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by webercm** [fidelram/deepTools#612] opened 2017-10-05 16:00 UTC
bamCoverage gives TypeError when run on paired-end bam but not single-end bam.
deeptools --version: deeptools 2.5.3 
Command:
bamCoverage --bam example.bam -o output.bam
        --binSize 1 \
        --normalizeTo1x 2150570000 \
        --ignoreForNormalization chrM ChrUn ChrRandom \
        --bl blacklistfile.bed;
Error:
 File "../bin/anaconda2/bin/bamCoverage", line 11, in <module>
    main(args)
  File "../bin/anaconda2/lib/python2.7/site-packages/deeptools/bamCoverage.py", line 145, in main
    scale_factor = get_scale_factor(args)
  File "../bin/anaconda2/lib/python2.7/site-packages/deeptools/getScaleFactor.py", line 168, in get_scale_factor
    bam_mapped, bam_mapped_total = get_num_kept_reads(args)
  File "/../bin/anaconda2/lib/python2.7/site-packages/deeptools/getScaleFactor.py", line 151, in get_num_kept_reads
    args.blackListFileName, args.numberOfProcessors)
  File "../bin/anaconda2/lib/python2.7/site-packages/deeptools/utilities.py", line 406, in bam_blacklisted_reads
    res = pool.map_async(bam_blacklisted_worker, regions).get(9999999)
  File "../bin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

**Comment by dpryan79** [comment] 2017-10-05 16:45
I wonder if this happens if there are no blacklisted alignments. Can you make a problematic BAM file and the blacklisted regions (privately) available to me?

**Comment by dpryan79** [comment] 2017-10-06 08:31
It looks like this happens whenever an unmapped alignment is given coordinates in a blacklisted region. I just need to skip those.

**Comment by dpryan79** [comment] 2017-10-06 10:09
This is now fixed for the next release.

**Comment by webercm** [comment] 2017-10-19 16:44
FYI - I get similar error without -bl flag.

Command:
bamCoverage --bam example.bam -o example.bw
        --binSize 10 \
        --normalizeTo1x 2150570000 \
        --ignoreForNormalization chrM ChrUn ChrRandom

Error:
 File "../bin/anaconda2/bin/bamCoverage", line 11, in <module>
    main(args)
  File "../bin/anaconda2/lib/python2.7/site-packages/deeptools/bamCoverage.py", line 145, in main
    scale_factor = get_scale_factor(args)
  File "../bin/anaconda2/lib/python2.7/site-packages/deeptools/getScaleFactor.py", line 179, in get_scale_factor
    verbose=args.verbose)
  File "../bin/anaconda2/lib/python2.7/site-packages/deeptools/getFragmentAndReadSize.py", line 134, in get_read_and_fragment_length
    'mean': np.mean(read_length),
  File "../anaconda2/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2889, in mean
    out=out, **kwargs)
  File ".../anaconda2/lib/python2.7/site-packages/numpy/core/_methods.py", line 70, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims)
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

When will update addressing these issue be released?

**Comment by dpryan79** [comment] 2017-10-19 17:51
Do you get this error with the same BAM file or is this a different one?

The next release got delayed so we can make some more drastic changes in it. I expect it'll be out in mid-November at this point.

**Comment by webercm** [comment] 2017-10-19 18:03
This is a different BAM file. Ok, seems that I will need to change my
pipelines.

Chris

**Comment by dpryan79** [comment] 2017-10-19 18:19
Can you make a small section of this other BAM file available? If this isn't triggered by the blacklist code then it's probably some other place that needs fixed.

**Comment by dpryan79** [comment] 2017-10-19 18:20
Given how annoying this bug is, perhaps I can just quickly release a patched version with only this issue (both the black list issue and this one) fixed.

**Comment by dpryan79** [comment] 2017-10-19 18:52
I think I found the part of the code that's causing this. I think I've now fixed the issue in a number of places. Is it possible for you to install the `hotfix/2.5.4` branch for testing (something like `pip install git+https://github.com/fidelram/deepTools@hotfix/2.5.4`)?

**Comment by webercm** [comment] 2017-10-19 21:37
Hi Devon,

Thanks again for your help and sorry for the late reply, I was in a long
meeting.

I'm not familiar with hotfix, so forgive me if I did something stupid. I
get the error below when I install with pip. I got the same error that was
reported to Github when I ran Deeptools after this.

-bash-4.1$ pip install git https://github.com/fidelram/
deepTools@hotfix/2.5.4

Collecting https://github.com/fidelram/deepTools@hotfix/2.5.4
  HTTP error 404 while getting https://github.com/fidelram/
deepTools@hotfix/2.5.4
  Could not install requirement https://github.com/fidelram/
deepTools@hotfix/2.5.4 because of error 404 Client Error: Not Found for
url: https://github.com/fidelram/deepTools@hotfix/2.5.4
Could not install requirement https://github.com/fidelram/
deepTools@hotfix/2.5.4 because of HTTP error 404 Client Error: Not Found
for url: https://github.com/fidelram/deepTools@hotfix/2.5.4 for URL
https://github.com/fidelram/deepTools@hotfix/2.5.4
-bash-4.1$ pip install git+https://github.com/fidelram/deepTools@hotfix/2.5.
4
Collecting git+https://github.com/fidelram/deepTools@hotfix/2.5.4
  Cloning https://github.com/fidelram/deepTools (to hotfix/2.5.4) to
/tmp/pip-XI3eSI-build
Requirement already satisfied: numpy>=1.9.0 in
./anaconda2/lib/python2.7/site-packages
(from deepTools==2.5.4)
Requirement already satisfied: scipy>=0.17.0 in
./anaconda2/lib/python2.7/site-packages
(from deepTools==2.5.4)
Requirement already satisfied: matplotlib>=1.4.0 in
./anaconda2/lib/python2.7/site-packages (from deepTools==2.5.4)
Requirement already satisfied: pysam>=0.8.2 in
./anaconda2/lib/python2.7/site-packages
(from deepTools==2.5.4)
Requirement already satisfied: numpydoc>=0.5 in
./anaconda2/lib/python2.7/site-packages
(from deepTools==2.5.4)
Requirement already satisfied: pyBigWig>=0.2.1 in
./anaconda2/lib/python2.7/site-packages
(from deepTools==2.5.4)
Exception:
Traceback (most recent call last):
  File "/home/webercm/bin/anaconda2/lib/python2.7/site-packages/pip/basecommand.py",
line 215, in main
    status = self.run(options, args)
  File "/home/webercm/bin/anaconda2/lib/python2.7/site-packages/pip/commands/install.py",
line 335, in run
    wb.build(autobuilding=True)
  File "/home/webercm/bin/anaconda2/lib/python2.7/site-packages/pip/wheel.py",
line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/webercm/bin/anaconda2/lib/python2.7/site-packages/pip/req/req_set.py",
line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/webercm/bin/anaconda2/lib/python2.7/site-packages/pip/req/req_set.py",
line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "/home/webercm/bin/anaconda2/lib/python2.7/site-packages/pip/utils/packaging.py",
line 48, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "/home/webercm/bin/anaconda2/lib/python2.7/email/feedparser.py",
line 177, in feed
    self._input.push(data)
  File "/home/webercm/bin/anaconda2/lib/python2.7/email/feedparser.py",
line 99, in push
    parts = data.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'

#########################################
I converted Sam to Bam using Samtools 1-6 like:
for j in *.sam
do
       outname=$(echo $j | sed 's/.sam//')
        samtools view -bS $j > $outname.bam &&
       samtools sort -n -o $outname-namesort.bam $outname.bam &&
       samtools fixmate -m $outname-namesort.bam $outname-fixmate.bam &&
       samtools sort -o $outname-positionsort.bam $outname-fixmate.bam &&
       samtools markdup -r -s $outname-positionsort.bam
$outname-mm10rmdup.bam

and then ran deeptools on the *-mm10rmdup.bam files

###########################################

**Comment by dpryan79** [comment] 2017-10-19 21:47
No clue about that error, can you make the BAM file available? I expect that branch fixes the issue but it'd make sense to be sure before pushing out the release.

**Comment by webercm** [comment] 2017-10-19 22:04
Sure. I started uploading a file (Fazzio_EGFP_KD_MNase-seq-mm10rmdup.bam)
that deepTools complains about to the same folder
<https://www.dropbox.com/sh/9skb6gyzd7buqyb/AAD7zGxepAj9n1WkCyhvGxLha?dl=0>
that
we shared in the past. Unfortunately the file is quite large and will take
awhile to scp.

Chris

**Comment by dpryan79** [comment] 2017-10-23 19:45
Interestingly, this only happens with python 2.7 and not with python 3, which is probably part of the reason I was having a hard time reproducing it. I can reproduce it now, so I'll release a patched version as soon as I can.

**Comment by webercm** [comment] 2017-10-24 15:32
Thanks! We really appreciate it.

**Comment by dpryan79** [comment] 2017-11-03 08:37
I'm pushing out version 2.5.4 right now, so this should then be fixed.

**Closed** 2017-11-03 08:37 UTC
Labels: bug
