### ISSUE TITLE
generalize handling of group information in BED files used by computeMatrix/plotProfile/plotHeatmap

### ISSUE THREAD

**Issue by steffenheyne** [fidelram/deepTools#278] opened 2016-02-08 09:46 UTC
Currently deepTools encodes group/cluster information in BED files with an additional line after each group with the format: "#\<GROUP_NAME\>". 

Group information is used to split up heatmaps (e.g. after clustering) or to summarize scores in different ways e.g. plotProfile.

This approach is working well in deeptools, but not really inline with the BED file format (or any column based format) and other tools like bedtools as these lines cannot be handled/added/modified etc by other "standard" tools.

Hence, I would suggest to use the bed format to encode group information which means encoding the group info in a certain column. As there is no real standardization after column 6 (or at least after column 12) we need an additional parameter to tell deeptools which column it should use as group information. 

In addition to use a specific column, we could also have something like "last" or "auto" which then takes the last column or is looking for some keywords (cluster, group...) in the first bed line and then decides which column is used. 

There are two main scenarios I see:
a) The user provides a bed file with group information and deepTools just should understand which column to use.

b) Group information is generated by deepTools (clustering) and it needs to be added to the bed file outputs

With a more general group encoding I also see easy, but powerful visulizations: e.g use column 1 and you group your regions according to the chromosomes.

Some thoughts: 
* Do we store the full (all columns) user provided bed file internally? 
* Do we also write out again all bed columns that were in input? (--outFileName / --outFileNameMatrix / --outFileSortedRegions)

To encode the groups in the matrix not much has to change as this is already in the header line, I think, right?

**Comment by dpryan79** [comment] 2016-02-08 10:51
I would be very hesitant to try automatic column group column detection. Since any number of columns in [3, 12] can be used in BED files, people are going to come up with creative an unintuitive ways to do this. If we're going to play around with this, then I would suggest just tacking the group on as an additional column. We then need to make clear that this is a BED-like format, which we should probably do anyway. Anything we do will break at least one other tool out there, so at least if we're forthright about the output not strictly being BED then people are somewhat forewarned.

BTW, we're currently basically ignoring most of the columns internally. However, that will need to be changed to deal with some of the other enhancement requests (namely #76). That'd be a nice feature to have.

This makes me appreciate Galaxy's "interval file" format, since that nicely captures what the format really is.

**Comment by friedue** [comment] 2016-02-08 22:26
I agree. It should be called INTERVALL format instead of BED. And including all the columns of the user's original file in the output would be great.

**Comment by fidelram** [comment] 2016-02-09 08:01
I advocate for the use of GTF (http://www.ensembl.org/info/website/upload/gff.html). The format is quite specific and has a field to define the groups that we want.

Deeptools, anyway, should be modified to accept GTF/GFF files (as many other programs do, including BEDtools). However, the output of sorted regions should be GTF to properly enconde the group id. 

Do you foresee any problem with this solution?

**Comment by steffenheyne** [comment] 2016-02-09 08:50
You would solely use GTF/GFF or in addition to some BED/interval-like file? Or only to provide special features to deeptools like the exon/intron encoding?

I think we should also support BED-12 files for the exon/intron encoding, here GTF is possible as well, but this gets all bit ugly for the user, or? 

For me the "beauty" of bed/interval-like files are that there is 1 interval per line, no joining over multiple lines etc...

So I would vote for an additional support of GTF files which definitely has is benefits too. Where you would encode the group-id? As attribute in col 9 or as feature (col 3)?

**Comment by dpryan79** [comment] 2016-02-09 08:51
@steffenheyne There's no way we could drop BED support!

**Comment by steffenheyne** [comment] 2016-02-09 08:54
ok, inline with my thinking...

**Comment by kilpert** [comment] 2016-02-09 09:06
I prefer the BED format, as it is much easier to handle on the command line in comparison to most other formats. However, the implementation of the current BED output should be improved:

1) All columns of the input file should remain in the output file, always.
2) The output file should have a header line (which is already part of the BED standard, starting with e.g.  '#'). Header lines are great because they clearly define the content. If the input file has no header line, we could just number the columns in the output file.
3) The big benefit of the header line is that we then can use it internally to define our own unambiguous columns, e.g 'deepTools_groups', which is exactly what we need to pass information.

By this, the output would be a file which is completely following the BED specification. If one, for some reason, doesn't like the additional header line, it is also so easy to get rid of it (by parsing it on the command line). We would be most flexible, without switching to a much more complex file format.

**Comment by fidelram** [comment] 2016-02-09 09:14
The idea is to support BED and GFF/GTF, but the output with clusters is only GFF. It could look like this:

```
chr1 deepTools  interval          380   401   .   +   .  gene_id=001;group_name=cluster_1;
chr1 deepTools  interval          501   650   .   -   .  gene_id=002;group_name=cluster_2;
```

**Comment by kilpert** [comment] 2016-02-09 09:20
Example for BED file with header:

Input:

1	11868	14409	ENST00000456328	0	+	14409	14409	0	3	359,109,1189,	0,744,1352,
1	12009	13670	ENST00000450305	0	+	13670	13670	0	6	48,49,85,78,154,218,	0,169,603,965,1211,1443,

Output:

# chrom	chromStart	chromEnd	4	5	6	7	8	9	10	11	12	deepTools_cluster
1	11868	14409	ENST00000456328	0	+	14409	14409	0	3	359,109,1189,	0,744,1352,	1
1	12009	13670	ENST00000450305	0	+	13670	13670	0	6	48,49,85,78,154,218,	0,169,603,965,1211,1443,	2

**Comment by steffenheyne** [comment] 2016-02-09 09:30
@fidelram What would you do with all the other columns maybe provided by the user in the bed-like file? You would encode all these as attributes like this?

chr1 deepTools  interval          380   401   .   +   .  col4=001; col5=0,col6="+",col7="myfeature";group_name=cluster_1;

not doing this would mean just another file which has to be joint/intersected afterwards to get the group-id to the input file from the user.

Whatever is provided by the user as input file we should have in output, plus the new information generated by deeptools...

**Comment by dpryan79** [comment] 2016-02-09 09:31
There's a nice mapping between BED12 and GFF, so that takes care of itself.

**Comment by kilpert** [comment] 2016-02-09 09:39
I am also fine with GTF/GFF. But I recommend to handle BED as described in my comments. GTF/GFF would be nice to have in addition.

**Comment by steffenheyne** [comment] 2016-02-10 13:26
so my understanding of a summary would be:

1) GTF/GFF is nice to have, but not necessary yet, and we adapt deeptool's interval file format to our needs

2.) We call the input/output formats of tables etc rather "interval" than BED

3.) to be compatible with BED, we should enforce the first 6 columns in deeptools: chr/start/end/name/score/strand; otherwise we get problems with the strand info, which is used currently if provided

4.) we pass-through all user provided columns, ie. also into deeptool's internal matrix format (gzipped), sanity check: all rows have to have the same number of cols

5.) we add header lines to all text-output files (can be skipped by option!?)

6.) in cases we need bed12, we support it, like in compute matrix: summarize only over full/exon/intron regions

7.) cluster information is added as new last column

8.) plotHeatmap/plotProfile also allows for a user-provided column to use as group-id

**Comment by dpryan79** [comment] 2016-02-15 13:42
XREF #76, which this is largely a duplicate of.

**Comment by friedue** [comment] 2016-02-24 14:55
For Galaxy users, GFF files are rather painful because of the differing field separators, INTERVAL would be much preferred there. For example, just getting the simple information about how many clusters there are in the output is easy with an INTERVAL file, while the GFF file would require more wrestling.
That being said, the current implementation with generating a non-standard BED file does not work well in Galaxy since it will simply make all non-standard rows into comments, which defies the purpose and forces the user to manually convert the file to INTERVAL anyway.

That being said, I agree that on the command line, the GFF output might be preferable (although I disagree with Fidel's opinion that the format is "well defined" -- it's a huge mess! There's GFF in various versions and GTF, which is based on GFF version 2, but slightly different...)

**Comment by lelouar** [comment] 2016-02-24 22:56
maybe an other file with 2 column with only name and cluster Id will solve this issue. If the bed file have only 3 col then you can join them and add cluster ID.

**Comment by dpryan79** [comment] 2016-04-01 13:54
A bit of an update on this. The `develop` branch now supports GTF and BED12 files and can store and compute metrics over the exons (concatenated into a transcript). The output of computeMatrix will have the exon bounds in it, if one uses the `--metagene` option. The score and anything > column 6 are currently not stored either in memory or in the file and doing so would largely just waste space/memory. Consequently, I would propose to standardize on BED12 output with the proposed header, though noting the columns 5 and 7-9 are not stored and can't be derived (but really, who cares about them?). Column13 would then be the group label and indicated as such in the header.

If it's really really important to someone I can have the score filled in as well, doing so currently just wastes memory since we don't use it for anything.

**Comment by steffenheyne** [comment] 2016-04-01 14:24
With score you mean the average over all bins (for all tracks) in the matrix? Filled in as column 5? 

This feature was once there and it was kind of nice for me for further filtering etc, but probably mostly useful in the single bigwig case. But on the other hand one column of values shouldn't take too much more memory...

**Comment by dpryan79** [comment] 2016-04-03 13:42
The score as in whatever was originally in column 5. I'll play around on monday with adding the score in as well. Aside from that, I had a couple minutes today and implemented the rest of this. It's now merged into the `develop` branch. Once I have the score from the original files stored and output as well I'll close this.

**Comment by dpryan79** [comment] 2016-04-04 12:42
Now the score is stored and output as well.

**Closed by dpryan79** 2016-04-04 12:42 UTC
Labels: enhancement
