### ISSUE TITLE
preparation for 2.0 release

### ISSUE THREAD

**Issue by bgruening** [fidelram/deepTools#208] opened 2016-01-05 11:21 UTC
Short check list for all things we need to do before and after we release.

 * [x] tag a github release [Fidel]
 * [x] upload to pypi [Fidel]
 * [x] conda build [Bjoern or Devon]
 * [x] Galaxy TTS and MTS update [Bjoern]
 * [x] Docker Image update (ngs-preprocessing and deeptools image) [Bjoern]
 * [x] migrate deeptools2 to deeptools [Devon]
 * [x] usegalaxy.org installation [Bjoern]
 * [x] automated internal testing of all tools [Fidel and Devon]
 * [X] Update wiki to reference read the docs [Devon]
 * [x] Screen-cast for the galaxy webpage [Fidel]

**Comment by bgruening** [comment] 2016-01-05 11:21
Please feel to disagree and/or add remove items.

**Comment by dpryan79** [comment] 2016-01-05 11:25
+1 We need to have an internal discussion about the last features that need to be added (my only suggestion would be remote file access, which is why I'm working on it now). I would also vote for automated internal testing, but I'm flexible on that one.

**Comment by bgruening** [comment] 2016-01-05 11:25
Oh and a release date would be nice to coordinate this :)

**Comment by dpryan79** [comment] 2016-01-11 14:23
We're shooting for 2 weeks until release.

**Comment by vivekbhr** [comment] 2016-01-11 21:52
Two features that I think should to be added in near future:
1. A set of contrasting colours + alternating line types in bamFP, which will solve #80 . (maybe before 2.0 release)
2. A general GTF file parser, which will solve #71 #76  (for the next release).

**Comment by bgruening** [comment] 2016-01-11 22:16
@vivekbhr I would create separate issues for this and tag them with a potential milestone. I wouldn't include any new features at this point. We can create a 2.1 release real quick if we like to, but we need to get this baby out, imho.

**Comment by dpryan79** [comment] 2016-01-11 22:22
Agreed, these features will should be 2.1. This thing has been in development for 2 years without a release, that's more than long enough.

For what it's worth, I was going to assign #80 to myself, since that should hopefully be an easy fix. #71 is easy if we just use "transcript" entries. I think #76 would take rather more effort that it might appear, though I agree it would be nice.

**Comment by lelouar** [comment] 2016-01-12 10:01
what you think of this feature for release 2.0 ? #108

**Comment by dpryan79** [comment] 2016-01-12 10:03
@lelouar: It won't be done in time for 2.0. That's a good feature for 2.1 though.

**Comment by fidelram** [comment] 2016-01-12 10:50
I agree with the list and I will add the renaming of `bamCorrelate`,  `bigwigCorrelate`, `bamFingerprint`. For the last one the idea is to clarify that they make a plot and should be labelled accordingly like `plotFingerprint`. Since the input to make the `bamFingerprint` is virtually identical to the one used to plot the correlations we can simplify the process by requiring as input for `plotFingerprint` not a list of bam files but the output of `bigwigCorrelate` or `bamCorrelate`.

With respect to #80, an approach similar to what is done in `plotProfile` can be easily implemented which is basically to ask the user for the list of colors to be used.

**Comment by friedue** [comment] 2016-01-14 16:03
can you update me on the renaming plans:
* do you mean that the tool names will be changed for the release of 2.0?
* what will the new names be?
* will the new names be implemented in Galaxy, too, and should I henceforth use the new names already when referring to the tools in the Galaxy documentation?

**Comment by dpryan79** [comment] 2016-01-18 09:24
Bioconda is ready to go for both [Linux and OSX](https://travis-ci.org/bioconda/bioconda-recipes/builds/103066249). Just waiting on the release getting tagged and put on pypi.

**Comment by vivekbhr** [comment] 2016-01-18 11:02
@friedue we are not changing the names in 2.0 .. probably in 2.1..

**Comment by bgruening** [comment] 2016-01-18 11:06
@vivekbhr we changed the names in https://github.com/fidelram/deepTools/pull/220 and this is now in master, aka 2.0, isn't it?

**Comment by dpryan79** [comment] 2016-01-18 11:11
@bgruening Correct. It wasn't done for the initial Galaxy preview, but will for the actual release.

**Comment by vivekbhr** [comment] 2016-01-18 11:13
@bgruening @dpryan79 Oh! I totally missed that thread..

**Comment by dpryan79** [comment] 2016-01-18 11:15
@vivekbhr There are a lot of them, so that's unsurprising :)

**Comment by dpryan79** [comment] 2016-01-21 13:15
We essentially have all of the internal testing scripts gathered together and run, so I've checked that off.

@fidelram @bgruening: I don't see anything preventing tagging a release. I'm having some issues with the galaxy wrappers not working, but that doesn't really prevent tagging 2.0.0 IMO. If we're all in agreement with that then perhaps it's time to tag. Thoughts?

**Comment by fidelram** [comment] 2016-01-21 13:58
Let's do it. We already fulfilled all issues for the 2.0 milestone

**Comment by bgruening** [comment] 2016-01-21 14:09
:+1: for me as well. Than I can fix the wrappers and the Docker Images.

**Comment by vivekbhr** [comment] 2016-01-21 14:44
:+1:

**Comment by bgruening** [comment] 2016-01-21 14:58
It's out! @fidelram awesome!

Thanks all for this great release!

**Comment by dpryan79** [comment] 2016-01-21 15:02
I'm testing the bioconda recipe now.

**Comment by dpryan79** [comment] 2016-01-21 15:20
I have the PR into bioconda: https://github.com/bioconda/bioconda-recipes/pull/646

**Comment by bgruening** [comment] 2016-01-21 18:58
`docker pull quay.io/bgruening/galaxy-deeptools` has anything installed. Dockerhub makes trouble and is queueing my builds, but this will be resolved soonish hopefully. They are still migrating there services.

So this could be the final Docker release. I will make some smoke testing and release everything to the Main TS tomorrow if no one objects.

ping @dpryan79 @friedue

**Comment by dpryan79** [comment] 2016-01-21 21:35
@bgruening Thanks Galaxy is working happily now with the updated wrappers and the tagged 2.0.0 release :)

**Comment by bgruening** [comment] 2016-01-21 21:36
Awesome!

**Comment by dpryan79** [comment] 2016-01-22 09:55
I just announced the deeptools.ie-freiburg.mpg.de migration for Friday next week.

**Comment by dpryan79** [comment] 2016-01-22 09:57
We should discuss whether to keep the older versions after the migration. The normal default there would be, "but of course!", but since some of the names have changed, things like `bamCorrelate` will still show up and then be version 1.5.9. My proposal would be to just remove those old tools whose name changed. Thoughts?

**Comment by fidelram** [comment] 2016-01-22 12:13
humm. we need some brain storming to detect unforeseen consequences.

In galaxy, I understand that if a user wants to run a pipeline or re-execute a job, the version of the program is kept. Thus, even if the tools are deleted from the menu, users reproducing results should be directed to the previous version. Is that the case?

Now, what would happen if a user needs the previous version of deeptools to keep results consistent? Can this person still access an earlier version of deepTools even if not in the galaxy menu?

**Comment by dpryan79** [comment] 2016-01-22 12:20
DeepTools is now in bioconda and should work on OSX and Linux with it.

**Comment by dpryan79** [comment] 2016-01-22 12:24
@fidelram: Yeah, I would just remove them from the menu. Normally they can select the version of the tool they would want to use (it defaults to the most recent, or at least the most recent installed). However, things like bamCorrelate wouldn't be there, so they couldn't run them. Alternatively, we could leave them there, but then people would continue using them.

I'm not entirely sure how Galaxy determines that some tools are different versions of others, perhaps there some trickery that could be done there.

**Comment by bgruening** [comment] 2016-01-22 12:37
We changed all linage in deeptools 2.0 as the names changed. What we can do is to hide old deeptools from the menue, so they only work in old workflows or kind of. All new stuff is taking the new deeptools version.

**Comment by bgruening** [comment] 2016-01-22 12:37
@dpryan79 do you think we can push to Main TS?

**Comment by dpryan79** [comment] 2016-01-22 14:37
@bgruening: Yeah, we could just hide things, that'd be the simplest solution. Regarding pushing to the toolshed, I wan't to briefly test to make sure each tool runs. After that's done then I'll give a :+1:.

**Comment by dpryan79** [comment] 2016-01-22 15:02
Missed opportunity: @vivekbhr just pointed out that the name of multiBamCoverage is confusing. In hindsight it should have been multiBamSummary, which would further distinguish it from bamCoverage. Maybe in 2.1...

**Comment by dpryan79** [comment] 2016-01-22 15:17
Everything is getting a green light except plotPCA. I wonder if that's broken in the actual release...

**Comment by bgruening** [comment] 2016-01-22 15:18
It's not to late from my side. Just tag a new release, it's not yet in the TS and changing name later is even more confusing if the paper uses the old name.

**Comment by dpryan79** [comment] 2016-01-22 15:21
Yeah, plotPCA is broken in 2.0.0. I'll fix it real quick. If we want to change the name we can then tag 2.0.1 after doing so.

**Comment by dpryan79** [comment] 2016-01-22 15:30
I'll try to have an answer by tonight regarding the renaming. plotPCA now works (at least for me, though it'd be nice if someone double checked...). Then we can proceed with tagging a release and pushing to the TS

**Comment by fidelram** [comment] 2016-01-22 17:01
we can do another renaming. I agree that now is better than later. @friedue do you foresee any issues with the documentation?

**Comment by vivekbhr** [comment] 2016-01-22 17:05
Yah I also agree we should do it sooner..

**Comment by dpryan79** [comment] 2016-01-22 18:51
Shall we agree to just make multiBamCoverage multiBamSummary, to match multiBigwigSummary?

**Comment by dpryan79** [comment] 2016-01-22 18:53
Truth be told, multiBigwigSummary can now take a single file, but I would ignore that since it's such an obscure use-case.

**Comment by bgruening** [comment] 2016-01-22 19:42
+1 for renaming again.

**Comment by dpryan79** [comment] 2016-01-22 20:03
@fidelram: so does "multiBamSummary" work for you?
@thomasmanke: Thoughts?

I'm personally happy with the other names, though I guess if someone else wants another one renamed then it's sort of now or never...

**Comment by friedue** [comment] 2016-01-22 20:26
well, if multiBigwigSummary can now take single files, that name is sort of a misnomer now.... :-P

**Comment by dpryan79** [comment] 2016-01-22 20:41
@friedue Yeah, the only real benefit to the "multi" prefix is that it emphasizes that more than one file should normally be entered. multiBamCoverage could also take a single file (I assume, if not it's another trivial fix). The only thing is that the resulting npz files aren't useful with any of our tools (the only useful thing is to write bedGraph files with the text output).

**Comment by dpryan79** [comment] 2016-01-22 20:42
In fact, maybe they should print a warning if only a single file is provided and it isn't requested that the text file be written...

**Comment by friedue** [comment] 2016-01-22 20:53
yes, I like that! print a warning that yes, the tools will run, but the output will be useless unless the `--rawBlaOption` is chosen

**Comment by dpryan79** [comment] 2016-01-22 21:10
On the Galaxy side, though, I think it'd be best to continue with 2+ files. At least IMHO, since otherwise we'll get questions about this every day.

**Comment by thomasmanke** [comment] 2016-01-22 22:11
Here is my vote for renaming to multi*Summary.

As for the multiBigWigSummary with single bw-file, I had only recently noticed that this has the potential to replace UCSCtools bigwigAverageOverBed - and it is way faster, thanks to Devon's efforts. For the biostars among us, we might even advertise it there (see: https://www.biostars.org/p/13802)
If we stick to 2+ files we cannot offer anything of that sort. If you feel this generates too much confusion, we could also leave it to 2.0.1 ....

**Comment by friedue** [comment] 2016-01-22 22:30
* def. do not offer single files in Galaxy for use with multi*Summary tools
* personally, I don't think that the name has to capture all aspects of the tool -- it's just a name! maybe, we should give non-descriptive names to future tools, hence avoiding these kinds of discussion (and enabling wonderful bug reports such as: "Erwin is running and running and not returning anything!" or "Kai-Uwe doesn't let me download results!")

**Comment by thomasmanke** [comment] 2016-01-22 22:31
I had tested plotPCA (successfully) using deepTools under /package/deepTools-2.0.0/,
but this version must have been out of sync. 
Now /package is also out of sync (and plotPCA fails as reported by Devon). But together with Fidel we 
tested the latest version and confirm that plotPCA works as intended.

**Comment by thomasmanke** [comment] 2016-01-22 22:33
;-) .  @friedue would be my name of choice for any new tool. And I will ask you to write its docu. Hilarious!!!

**Comment by dpryan79** [comment] 2016-01-23 08:19
OK, we'll stick to multi*Summary. I have a branch that should allow multi*Summary to take a single file and then produce a warning if --outRawCounts isn't used. That would need to be tested (and the bane of my existence, PEP8 conformance, fixed), but then we can do a quick rename.

**Comment by dpryan79** [comment] 2016-01-25 12:55
@bgruening 2.0.1 is now out and plotPCA should be fixed (and multiBamCoverage renamed). Fidel is uploading to pypi now, so you should be able to bump the Galaxy wrapper versions shortly. I'll then retest plotPCA and multiBamSummary in Galaxy and (presumably) give a green light for pushing to the toolshed.

BTW, for the Galaxy package I would recommend getting the version from pypi rather than github, it'll be a much smaller download.

**Comment by bgruening** [comment] 2016-01-25 18:16
I'm not able to find the download link in pypi. The deeptools pypi page looks strange to me compared to other projects. Any idea what’s wrong here @fidelram ?

**Comment by dpryan79** [comment] 2016-01-25 18:56
Yeah, I've been assuming that @fidelram somehow disabled the files section on pypi. Anyway, the link is here:  https://pypi.python.org/packages/source/d/deepTools/deepTools-2.0.1.tar.gz

**Comment by bgruening** [comment] 2016-01-25 19:16
Imaging is building and is now bound to 16.01.

**Comment by dpryan79** [comment] 2016-01-25 19:26
:+1: Do you know what the ETA is on 16.01? I need to upgrade our internal instance and it'd make sense to wait until that's released.

**Comment by dpryan79** [comment] 2016-01-25 20:59
@bgruening The updated wrappers seem to work, though the version shows up as "2.0.1.0.0". If that's intentional then I would say you have a green light from our side to push to the TS!

**Comment by bgruening** [comment] 2016-01-26 01:34
This week? ;) Who knows but this was the plan afaik.
So deepTools is now in the MTS and I updated all Docker containers again to get the latest version from MTS.

This **is** exciting!

**Comment by fidelram** [comment] 2016-01-26 07:54
@bgruening I have not disabled anything in pypi. I am surprised that it does not work I will check that that could be. My test always was to run pip install deeptools and check that I get the latest version.

**Comment by bgruening** [comment] 2016-01-26 08:07
@fidelram is does work. The page just looks wired. Usually you have a list with tarballs and md5 checksum displayed very prominently on the main page.

**Comment by rpantier** [comment] 2016-01-28 18:59
The "save the underlying data" output option disappeared from plotProfile in Galaxy (DeepTools 2.0) compared to the original Profiler. Is it normal? (it doesn't appear on the documentation neither: http://deeptools.readthedocs.org/en/latest/content/tools/plotProfile.html)
Thanks!

**Comment by dpryan79** [comment] 2016-01-28 19:45
@rpantier That's normal, the feature was removed since it wasn't currently doing anything. See also #231

**Comment by dpryan79** [comment] 2016-01-28 19:50
@rpantier: BTW, since you found the test Galaxy instance I should warn you that it'll go away soon (I announced on the list that I'm upgrading the public deepTools Galaxy server tomorrow morning, at which point the instances will be identical). Since you have some datasets loaded I'll try to ensure that the test server stays up for another week, though :)

**Comment by rpantier** [comment] 2016-01-28 20:25
@dpryan79 Thanks for your quick reply (I will move my data tomorrow). I was hoping to use the "underlying data" table from the Profiler to calculate PolII traveling ratios.

**Comment by dpryan79** [comment] 2016-01-28 20:31
@rpantier Sounds reasonable. Regarding the text files from plotProfile et al., the squeaky wheel does tend to get the grease and you're not alone in asking for this ;p

**Comment by dpryan79** [comment] 2016-01-29 13:25
deeptools.ie-freiburg.mpg.de has now been upgraded :)

Many thanks to @bgruening for the last minute galaxy toolshed updates!

@bgruening: Upgrading the docker images is indeed quite simple. I should note that for whatever reason, the DB migration script tossed a really nasty error message on the last DB version migration step (130->131, I think and it was complaining about trying to create a table that already existed). It worked non-the-less.

**Comment by bgruening** [comment] 2016-01-29 13:43
@dpryan79 do you have the error report? But if it does work ... :) Great!
Let me know if there is anything complicated that we should document in the Docker project.

**Comment by dpryan79** [comment] 2016-01-29 14:51
@bgruening Not anymore, but I have a database dump, so I'll see if I can reproduce it on a different server. If I can I'll create a galaxy issue.

**Comment by vivekbhr** [comment] 2016-03-01 16:44
I found 11 open issues, so I am closing this to round that number.. :+1: 

Also because release 2.2 is out today..

**Closed by vivekbhr** 2016-03-01 16:44 UTC
